### ISSUE TITLE
no names ):

### ISSUE THREAD

**Issue by fady1234** [MadProbe/Yapped-Rune-Bear#2]
![image](https://github.com/MadProbe/Yapped-Rune-Bear/assets/54465219/8155fd9d-2483-4579-8e96-8c8a747b40f9)

**Comment by MadProbe** [comment]
Sorry, but I can't do anything with that as it's not possible to give a meaningful name to every entry in the whole parambnd and even 10 people can fill out every name to each entry in a year and there are only some of them are named and to name every one of them one needs to figure out what each param changes.
Also sorry for late reply but I have seen it earlier and just haven't done anything with this until this moment.
I am closing this as `wontfix` as I don't have time for this and this will take my whole life to do this.
Also there are other games and not just Elden Ring.
